swagger: "2.0"
info:
  version: "0.0.1"
  title: Intapp DOCS
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/vnd.openxmlformats-officedocument.wordprocessingml.document
paths:
  /convert:
    # binds a127 app logic to a route
    x-swagger-router-controller: doc_process
    get:
      description: Converts the document in /Templates/ folder to the /Output folder
      # used as the method name of the controller
      operationId: convert
      parameters:
        - name: templateName
          in: query
          description: The name of the template document (e.g., "AML Cert - IntApp.docx")
          required: true
          type: string
        - name: replacementJson
          in: query
          description: Replacement pairs in the template document to convert. (e.g., {"firstname":"Joe", "lastname":"Smith"})
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DocConvertResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /convert_bulk:
    x-swagger-router-controller: doc_process
    post: 
      description: Converts the document in /Templates/ folder to the /Output folder
      # used as the method name of the controller
      operationId: convert_bulk
      parameters:
        - name: templateName
          in: query
          description: The name of the template document (e.g., "AML Cert - IntApp.docx")
          required: true
          type: string
        - name: replacementJson
          in: formData
          description: Replacement pairs in the template document to convert. (e.g., {"firstname":"Joe", "lastname":"Smith"})
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DocConvertResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /download:
    # binds a127 app logic to a route
    x-swagger-router-controller: doc_process
    get:
      description: Downloads the document in the /Output/ folder
      # used as the method name of the controller
      operationId: download
      parameters:
        - name: documentName
          in: query
          description: The name of the converted document (e.g., "AML Cert - IntApp.docx")
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DocConvertResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /convertToFile:
    # binds a127 app logic to a route
    x-swagger-router-controller: doc_process
    get:
      description: Converts the document in /Templates/ folder and downloads the document
      # used as the method name of the controller
      operationId: convertToFile
      parameters:
        - name: templateName
          in: query
          description: The name of the template document (e.g., "AML Cert - IntApp.docx")
          required: true
          type: string
        - name: replacementJson
          in: query
          description: Replacement pairs in the template document to convert (e.g., {"firstname":"Joe", "lastname":"Smith"})
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DocConvertResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DocConvertResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
